artifact_library: lightning_checkpoints
batch_config: configs/batch_gpu_default.yaml
batch_setup: true
callbacks: null
config: gnn_test.yaml
datatype_names:
- train
- val
- test
datatype_split:
- 9000
- 1000
- 5000
delta_eta: 1.2
edge_cut: 0.5
emb_channels: 0
endcaps: true
factor: 0.3
hidden: 64
hidden_activation: ReLU
in_channels: 3
inference: false
input_dir: /global/cscratch1/sd/ianwang/data/HSF/10k+5k/filter_processed/
layernorm: true
logger: tb
lr: 0.001
max_epochs: 100
model_library: LightningModules
n_graph_iters: 8
name: ResAGNN
nb_edge_layer: 3
nb_node_layer: 3
noise: true
output_dir: /global/cscratch1/sd/ianwang/data/HSF/10k+5k/gnn_processed/
overwrite: true
patience: 20
project: LRT(GNN)
pt_background_min: 0.0
pt_signal_min: 0.0
regime: pid
resume_id: null
set: GNN
slack_alert: false
true_edges: layerless_true_edges
warmup: 450
weight: 2
