# Input/output configuration
input_dir: ${SCRATCH}/data/HSF/10k+5k/filter_processed/
output_dir: ${SCRATCH}/data/HSF/10k+5k/gnn_processed/
project: LRT(GNN)
edge_cut: 0.5
overwrite: True

# Dataset parameters
pt_background_min: 0.0
pt_signal_min: 0.0
datatype_names: [[train, val, test]] # Which directory prefixes to use, assuming at least a train dataset 
datatype_split: [[9000, 1000, 5000]] # Number of [training, validation, testing] examples
endcaps: True
true_edges: layerless_true_edges
noise: True

# Model parameters
in_channels: 3
hidden: 64
n_graph_iters: 8
nb_node_layer: 3
nb_edge_layer: 3
emb_channels: 0
layernorm: True
hidden_activation: ReLU
weight: 2
delta_eta: 1.2
warmup: 450
lr: 0.001
factor: 0.3
patience: 20
regime: [[pid]]
max_epochs: 100
slack_alert: False

checkpoint_path: ${HOME}/HSFPipeline/Tracking-ML-Exa.TrkX/Pipelines/LRT/lightning_checkpoints/LRT(GNN)/version_0/checkpoints/last.ckpt

# Post-processing
callbacks: #[GNNInferenceCallback]
